#spring:
#  profiles:
#    active: dev
swagger:
  production: false
  basic:
    enable: true
    username: admin
    password: 123456
jeecg :
  path :
    #文件上传根目录 设置
    upload: /data/upload
    #webapp文件路径
    webapp: /data/upload
  shiro:
    excludeUrls: /test/jeecgDemo/demo3,/test/jeecgDemo/redisDemo/**,/carousel/wbCarousel/list,/sys/getPhoneSmsCode
  mini-program:
    appId: wx424640421193d7af
    appSecret: cb4a03fe66264afcf94e83f90e1f096c
  mobile:
    appId: wx424640421193d7af
    appSecret: cb4a03fe66264afcf94e83f90e1f096c
